#server.port= 8081
#server.servlet.context-path=/zjlong
server:
  port: 8081
  servlet:
    context-path: /zjlong
spring:
  application:
    name: study-jdbc
#  datasource:
#    url: jdbc:mysql://127.0.0.1:3306/usercenter?characterEncoding=utf-8
#    username: root
#    password: 123456
#    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    time-zone: GMT+8
  main:
    allow-bean-definition-overriding: true
  shardingsphere:
    props:
      sql:
        show: true
    datasource:
      names: ds1,ds2
      ds1:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3307/test?characterEncoding=utf-8&useSSL=false
        username: root
        password: 123456
        maxPoolSize: 100
        minPoolSize: 5

      ds2:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3308/test?characterEncoding=utf-8&useSSL=false
        username: root
        password: 123456
        maxPoolSize: 100
        minPoolSize: 5
    sharding:
      #配置默认数据源
      default-data-source-name: ds1
    #非数据分片的读写分离配置
    masterslave:
      #配置主从名称，可以任意取名字
      name: ms
      #配置slave节点的负载均衡策略，采用轮询机制,随机random
      load-balance-algorithm-type: round_robin
      master-data-source-name: ds1
      slave-data-source-names: ds2



mybatis:
#  config-location: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.zjlong.studyjdbc.business.entity